Repository FC-InnerCircle-ICD2/fintech-BE, pull requests merged in 2025-02, with the labels that each got.

#159 DataClass 직렬화 문제 해결
  api/build.gradle.kts
  api/src/main/kotlin/com/inner/circle/api/config/ObjectMapperConfig.kt
  api/src/test/kotlin/com/inner/circle/api/jackson/SerializationTest.kt
Labels: FEAT

#181 feat: 상점 인증 Spring Security 구현
  api/src/main/kotlin/com/inner/circle/api/security/MerchantApiKeyAuthenticationFilter.kt
  api/src/main/kotlin/com/inner/circle/api/security/SecurityConfig.kt
  core/src/main/kotlin/com/inner/circle/core/security/MerchantApiKeyProvider.kt
  core/src/main/kotlin/com/inner/circle/core/security/MerchantApiKeyProviderImpl.kt
  core/src/main/kotlin/com/inner/circle/core/security/MerchantDetailService.kt
  core/src/main/kotlin/com/inner/circle/core/security/MerchantUserDetails.kt
  exception/src/main/kotlin/com/inner/circle/exception/UserAuthenticationException.kt
Labels: FEAT, REFACTOR

#178 feat: Acoount Entity 수정
  api/src/test/resources/sql/schema.sql
  infra/src/main/kotlin/com/inner/circle/infra/repository/entity/AccountEntity.kt
Labels: FEAT

#198 feat: User Account 인증 기능 구현
  api/src/main/kotlin/com/inner/circle/api/config/SwaggerConfig.kt
  api/src/main/kotlin/com/inner/circle/api/controller/merchant/MerchantPaymentController.kt
  api/src/main/kotlin/com/inner/circle/api/controller/user/UserPaymentController.kt
  api/src/main/kotlin/com/inner/circle/api/security/SecurityConfig.kt
  api/src/main/kotlin/com/inner/circle/api/security/UserApiAuthenticationFilter.kt
  api/src/main/resources/application.yaml
  core/src/main/kotlin/com/inner/circle/core/security/AccountDetails.kt
  core/src/main/kotlin/com/inner/circle/core/security/AccountValidationProvider.kt
  core/src/main/kotlin/com/inner/circle/core/security/AccountValidationProviderManager.kt
  core/src/main/resources/application-core.yaml
  core/src/main/resources/application.yaml
  infra/src/main/kotlin/com/inner/circle/infra/adaptor/AccountFinderAdaptor.kt
  infra/src/main/kotlin/com/inner/circle/infra/port/AccountFinderPort.kt
  infra/src/main/kotlin/com/inner/circle/infra/repository/UserRepository.kt
Labels: FEAT

#202 feat: SSE 어노테이션 추가
  api/src/main/kotlin/com/inner/circle/api/config/SwaggerConfig.kt
  api/src/main/kotlin/com/inner/circle/api/controller/merchant/MerchantSseApiController.kt
Labels: FEAT

#205 155/user payment method - 유저의 대표 카드로 결제 승인 진행될 수 있도록 보완
  api/src/main/kotlin/com/inner/circle/api/controller/PaymentForMerchantV1Api.kt
  api/src/main/kotlin/com/inner/circle/api/controller/PaymentForUserV1Api.kt
  api/src/main/kotlin/com/inner/circle/api/controller/user/UserPaymentController.kt
  api/src/main/resources/application.yaml
  api/src/test/resources/sql/schema.sql
  core/src/main/kotlin/com/inner/circle/core/service/ConfirmPaymentService.kt
  core/src/main/kotlin/com/inner/circle/core/usecase/ConfirmSimplePaymentUseCase.kt
  infra/src/main/kotlin/com/inner/circle/infra/adaptor/ConfirmPaymentAdaptor.kt
  infra/src/main/kotlin/com/inner/circle/infra/port/ConfirmPaymentPort.kt
  infra/src/main/kotlin/com/inner/circle/infra/repository/UserCardJpaRepository.kt
  infra/src/main/kotlin/com/inner/circle/infra/repository/UserCardRepository.kt
  infra/src/main/kotlin/com/inner/circle/infra/repository/UserCardRepositoryImpl.kt
  infra/src/main/kotlin/com/inner/circle/infra/repository/entity/PaymentRequestEntity.kt
Labels: FEAT, FIX

#206 fix(155): 카드사 목서버 요청 오류 수정
  api/src/main/resources/application.yaml
Labels: FIX

#225 refactor(backoffice): Merchant sign-in 관련 로직 부분 수정
  api-backoffice/src/main/kotlin/com/inner/circle/apibackoffice/controller/MerchantController.kt
  api-backoffice/src/main/kotlin/com/inner/circle/apibackoffice/controller/dto/MerchantDto.kt
  core-backoffice/src/main/kotlin/com/inner/circle/corebackoffice/service/MerchantSaveService.kt
  core-backoffice/src/main/kotlin/com/inner/circle/corebackoffice/service/MerchantSignInService.kt
  core-backoffice/src/main/kotlin/com/inner/circle/corebackoffice/usecase/MerchantSaveUseCase.kt
  core-backoffice/src/main/kotlin/com/inner/circle/corebackoffice/usecase/MerchantSignInUseCase.kt
  infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/adaptor/CreateOrUpdateMerchantKeyAdaptor.kt
  infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/adaptor/MerchantFinderAdaptor.kt
  infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/adaptor/MerchantSaveAdaptor.kt
  infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/port/MerchantFinderPort.kt
  infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/port/MerchantSavePort.kt
  infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/repository/MerchantJpaRepository.kt
  infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/repository/MerchantRepository.kt
  infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/repository/MerchantRepositoryImpl.kt
  infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/repository/entity/MerchantEntity.kt
Labels: REFACTOR

#226 feat: User Login 기능 구현
  api/build.gradle.kts
  api/src/main/kotlin/com/inner/circle/api/config/BCryptPasswordEncoderConfig.kt
  api/src/main/kotlin/com/inner/circle/api/controller/dto/UserLoginResponse.kt
  api/src/main/kotlin/com/inner/circle/api/controller/request/UserLoginRequest.kt
  api/src/main/kotlin/com/inner/circle/api/controller/user/UserLoginController.kt
  api/src/main/kotlin/com/inner/circle/api/security/UserApiAuthenticationFilter.kt
  api/src/test/resources/sql/schema.sql
  core/src/main/kotlin/com/inner/circle/core/service/JwtHandler.kt
  core/src/main/kotlin/com/inner/circle/core/service/TokenHandlerService.kt
  core/src/main/kotlin/com/inner/circle/core/service/UserLoginService.kt
  core/src/main/kotlin/com/inner/circle/core/service/dto/AccountInfo.kt
  core/src/main/kotlin/com/inner/circle/core/usecase/TokenHandlerUseCase.kt
  core/src/main/kotlin/com/inner/circle/core/usecase/UserLoginUseCase.kt
  exception/src/main/kotlin/com/inner/circle/exception/UserAuthenticationException.kt
  gradle/libs.versions.toml
  infra/src/main/kotlin/com/inner/circle/infra/adaptor/AccountFinderAdaptor.kt
  infra/src/main/kotlin/com/inner/circle/infra/port/AccountFinderPort.kt
  infra/src/main/kotlin/com/inner/circle/infra/repository/UserRepository.kt
Labels: FEAT

#231 224/sse message type
  api/src/main/kotlin/com/inner/circle/api/application/PaymentStatusChangedMessageSender.kt
  api/src/main/kotlin/com/inner/circle/api/controller/user/UserPaymentController.kt
  core/src/main/kotlin/com/inner/circle/core/service/ConfirmPaymentService.kt
Labels: FIX, REFACTOR

#227 Infra/discord appender - pay200-be-pr 채널에 ERROR 로그 남기기
  api/build.gradle.kts
  api/src/main/kotlin/com/inner/circle/api/exception/GlobalExceptionHandler.kt
  api/src/main/resources/application.yaml
  api/src/main/resources/logback-spring.xml
  buildSrc/settings.gradle.kts
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: CHORE

#240 feat(payment): 간편 결제 유저 - 결제 내역 조회
  api/src/main/kotlin/com/inner/circle/api/controller/dto/PaymentType.kt
  api/src/main/kotlin/com/inner/circle/api/controller/dto/PaymentWithTransactionsDto.kt
  api/src/main/kotlin/com/inner/circle/api/controller/dto/TransactionDto.kt
  api/src/main/kotlin/com/inner/circle/api/controller/dto/TransactionStatus.kt
  api/src/main/kotlin/com/inner/circle/api/controller/user/UserPaymentController.kt
  core/src/main/kotlin/com/inner/circle/core/domain/PaymentTransaction.kt
  core/src/main/kotlin/com/inner/circle/core/domain/TransactionStatus.kt
  core/src/main/kotlin/com/inner/circle/core/service/TransactionService.kt
  core/src/main/kotlin/com/inner/circle/core/service/dto/PaymentWithTransactionsDto.kt
  core/src/main/kotlin/com/inner/circle/core/service/dto/TransactionDto.kt
  core/src/main/kotlin/com/inner/circle/core/usecase/GetPaymentWithTransactionsUseCase.kt
  exception/src/main/kotlin/com/inner/circle/exception/PaymentException.kt
  infra/src/main/kotlin/com/inner/circle/infra/adaptor/PaymentAdaptor.kt
  infra/src/main/kotlin/com/inner/circle/infra/adaptor/TransactionAdaptor.kt
  infra/src/main/kotlin/com/inner/circle/infra/adaptor/dto/TransactionDto.kt
  infra/src/main/kotlin/com/inner/circle/infra/port/GetPaymentPort.kt
  infra/src/main/kotlin/com/inner/circle/infra/port/GetTransactionPort.kt
  infra/src/main/kotlin/com/inner/circle/infra/repository/PaymentJpaRepository.kt
  infra/src/main/kotlin/com/inner/circle/infra/repository/PaymentRepository.kt
  infra/src/main/kotlin/com/inner/circle/infra/repository/PaymentRepositoryImpl.kt
  infra/src/main/kotlin/com/inner/circle/infra/repository/TransactionJpaRepository.kt
  infra/src/main/kotlin/com/inner/circle/infra/repository/TransactionRepository.kt
  infra/src/main/kotlin/com/inner/circle/infra/repository/TransactionRepositoryImpl.kt
Labels: FEAT

#252 fix(222): paymentToken 저장 - hashing 처리
  api/src/test/resources/sql/schema.sql
  core/src/main/kotlin/com/inner/circle/core/service/PaymentPaymentTokenHandleService.kt
  gradle/libs.versions.toml
  infra/build.gradle.kts
  infra/src/main/kotlin/com/inner/circle/infra/adaptor/PaymentTokenAdaptor.kt
  infra/src/main/kotlin/com/inner/circle/infra/adaptor/dto/PaymentClaimDto.kt
  infra/src/main/kotlin/com/inner/circle/infra/adaptor/dto/PaymentTokenDto.kt
  infra/src/test/kotlin/com/inner/circle/infra/adaptor/PaymentTokenTest.kt
  infra/src/test/kotlin/com/inner/circle/infra/repository/memorydatabase/PaymentTokenMemoryRepositoryTest.kt
Labels: FEAT, FIX

#260 fix(payment): TransactionDto 응답 반환 시 TSID String으로 변환
  api/src/main/kotlin/com/inner/circle/api/controller/dto/TransactionDto.kt
Labels: FIX

#261 243/app sse fix
  api/src/main/kotlin/com/inner/circle/api/controller/user/UserSseApiController.kt
Labels: REFACTOR

#262 fix(258): jwt payload 내 merchantId를 추가
  core/src/main/kotlin/com/inner/circle/core/service/JwtHandler.kt
Labels: REFACTOR

#268 feat(backoffice): 간편 결제 유저 - 전체 결제 내역 조회
  api-backoffice/src/main/kotlin/com/inner/circle/apibackoffice/controller/PaymentController.kt
  api-backoffice/src/main/kotlin/com/inner/circle/apibackoffice/controller/dto/PaymentWithTransactionsDto.kt
  api-backoffice/src/main/kotlin/com/inner/circle/apibackoffice/controller/dto/PaymentsWithTransactionsDto.kt
  api-backoffice/src/main/kotlin/com/inner/circle/apibackoffice/controller/dto/TransactionDto.kt
  api/src/main/kotlin/com/inner/circle/api/controller/dto/TransactionDto.kt
  core-backoffice/src/main/kotlin/com/inner/circle/corebackoffice/domain/PaymentTransaction.kt
  core-backoffice/src/main/kotlin/com/inner/circle/corebackoffice/service/PaymentService.kt
  core-backoffice/src/main/kotlin/com/inner/circle/corebackoffice/service/TransactionService.kt
  core-backoffice/src/main/kotlin/com/inner/circle/corebackoffice/service/dto/PaymentWithTransactionsDto.kt
  core-backoffice/src/main/kotlin/com/inner/circle/corebackoffice/service/dto/TransactionDto.kt
  core-backoffice/src/main/kotlin/com/inner/circle/corebackoffice/usecase/GetPaymentWithTransactionsUseCase.kt
  core-backoffice/src/main/kotlin/com/inner/circle/corebackoffice/usecase/GetTransactionUseCase.kt
  infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/adaptor/PaymentAdaptor.kt
  infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/adaptor/TransactionAdaptor.kt
  infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/adaptor/dto/TransactionDto.kt
  infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/port/GetPaymentPort.kt
  infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/port/GetTransactionPort.kt
  infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/repository/PaymentJpaRepository.kt
  infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/repository/PaymentRepository.kt
  infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/repository/PaymentRepositoryImpl.kt
  infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/repository/TransactionJpaRepository.kt
  infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/repository/TransactionRepository.kt
  infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/repository/TransactionRepositoryImpl.kt
  infra/src/main/kotlin/com/inner/circle/infra/repository/PaymentRepositoryImpl.kt
Labels: FEAT

#273 fix(payment): transaction requestedAt 값 설정 로직 수정
  infra/src/main/kotlin/com/inner/circle/infra/adaptor/TransactionAdaptor.kt
  infra/src/main/kotlin/com/inner/circle/infra/repository/TransactionRepository.kt
  infra/src/main/kotlin/com/inner/circle/infra/repository/TransactionRepositoryImpl.kt
Labels: FIX

#266 feat: 현재 로그인한 회원 정보 조회 API 구현
  api/src/main/kotlin/com/inner/circle/api/controller/dto/UserInfoResponse.kt
  api/src/main/kotlin/com/inner/circle/api/controller/user/UserLoginController.kt
Labels: FEAT

#278 274/sse connection in ttl - App 측 (결제 고객) sse 연결은 payment가 살아있는 동안에만 유효하다.
  api/src/main/kotlin/com/inner/circle/api/application/PaymentStatusChangedMessageSender.kt
  api/src/main/kotlin/com/inner/circle/api/controller/merchant/MerchantSseApiController.kt
  api/src/main/kotlin/com/inner/circle/api/controller/user/UserSseApiController.kt
  core/src/main/kotlin/com/inner/circle/core/service/PaymentPaymentTokenHandleService.kt
  core/src/main/kotlin/com/inner/circle/core/usecase/PaymentTokenHandlingUseCase.kt
  exception/src/main/kotlin/com/inner/circle/exception/SseException.kt
  infra/src/main/kotlin/com/inner/circle/infra/adaptor/PaymentClaimAdaptor.kt
  infra/src/main/kotlin/com/inner/circle/infra/adaptor/PaymentTokenAdaptor.kt
  infra/src/main/kotlin/com/inner/circle/infra/port/PaymentTokenHandlingPort.kt
  infra/src/main/kotlin/com/inner/circle/infra/repository/entity/PaymentTokenRepository.kt
  infra/src/main/kotlin/com/inner/circle/infra/repository/memorydatabase/PaymentTokenMemoryRepository.kt
Labels: FEAT

#279 feat(payment): 결제 내역 조회 시간 필터링 추가
  api-backoffice/src/main/kotlin/com/inner/circle/apibackoffice/controller/dto/PaymentWithTransactionsDto.kt
  api-backoffice/src/test/resources/sql/schema.sql
  api/src/main/kotlin/com/inner/circle/api/controller/dto/PaymentWithTransactionsDto.kt
  api/src/main/kotlin/com/inner/circle/api/controller/dto/TransactionStatus.kt
  api/src/main/kotlin/com/inner/circle/api/controller/user/UserPaymentController.kt
  api/src/main/kotlin/com/inner/circle/api/exception/GlobalExceptionHandler.kt
  api/src/test/resources/sql/schema.sql
  core/src/main/kotlin/com/inner/circle/core/service/TransactionService.kt
  core/src/main/kotlin/com/inner/circle/core/usecase/GetPaymentWithTransactionsUseCase.kt
  infra/src/main/kotlin/com/inner/circle/infra/adaptor/PaymentAdaptor.kt
  infra/src/main/kotlin/com/inner/circle/infra/port/GetPaymentPort.kt
  infra/src/main/kotlin/com/inner/circle/infra/repository/PaymentJpaRepository.kt
  infra/src/main/kotlin/com/inner/circle/infra/repository/PaymentRepository.kt
  infra/src/main/kotlin/com/inner/circle/infra/repository/PaymentRepositoryImpl.kt
Labels: FEAT

#290 feat(backoffice): 결제 내역 조회 필터링 추가
  api-backoffice/src/main/kotlin/com/inner/circle/apibackoffice/controller/PaymentController.kt
  api-backoffice/src/main/kotlin/com/inner/circle/apibackoffice/controller/dto/TransactionStatus.kt
  api/src/test/resources/sql/schema.sql
  core-backoffice/src/main/kotlin/com/inner/circle/corebackoffice/service/TransactionService.kt
  core-backoffice/src/main/kotlin/com/inner/circle/corebackoffice/usecase/GetPaymentWithTransactionsUseCase.kt
  core/src/main/kotlin/com/inner/circle/core/service/TransactionService.kt
  infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/adaptor/PaymentAdaptor.kt
  infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/port/GetPaymentPort.kt
  infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/repository/PaymentJpaRepository.kt
  infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/repository/PaymentRepository.kt
  infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/repository/PaymentRepositoryImpl.kt
Labels: FEAT

#298 fix(payment, backoffice): payment 정렬 쿼리 수정
  core-backoffice/src/main/kotlin/com/inner/circle/corebackoffice/service/TransactionService.kt
  core/src/main/kotlin/com/inner/circle/core/service/TransactionService.kt
  infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/repository/PaymentRepositoryImpl.kt
  infra/src/main/kotlin/com/inner/circle/infra/repository/PaymentRepositoryImpl.kt
Labels: REFACTOR

#295 fix(payment): user 인증 오류 시 메시지 출력
  api/src/main/kotlin/com/inner/circle/api/security/CustomAuthenticationEntryPoint.kt
  api/src/main/kotlin/com/inner/circle/api/security/MerchantApiKeyAuthenticationFilter.kt
  api/src/main/kotlin/com/inner/circle/api/security/SecurityConfig.kt
  api/src/main/kotlin/com/inner/circle/api/security/UserApiAuthenticationFilter.kt
Labels: FIX

#292 222/request amount limit to 100 million
  api/src/main/kotlin/com/inner/circle/api/controller/merchant/MerchantPaymentController.kt
  api/src/main/kotlin/com/inner/circle/api/controller/request/PaymentApproveRequest.kt
  api/src/main/kotlin/com/inner/circle/api/controller/request/PaymentClaimRequest.kt
Labels: FEAT

#294 fix(287): 예외 메시지가 보완되어야 할 구간 보완
  core-backoffice/src/main/kotlin/com/inner/circle/corebackoffice/service/JwtHandler.kt
  core/src/main/kotlin/com/inner/circle/core/service/JwtHandler.kt
Labels: REFACTOR

#297 fix(161): discord-appender 추가 - backoffice
  api-backoffice/src/main/resources/application.yaml
  api-backoffice/src/main/resources/logback-spring.xml
Labels: FEAT

#301 300/card not found
  api/src/main/kotlin/com/inner/circle/api/security/MerchantApiKeyAuthenticationFilter.kt
  core/src/main/kotlin/com/inner/circle/core/service/ConfirmPaymentService.kt
  exception/src/main/kotlin/com/inner/circle/exception/HttpStatus.kt
  exception/src/main/kotlin/com/inner/circle/exception/PaymentException.kt
  infra/src/main/kotlin/com/inner/circle/infra/http/HttpClient.kt
Labels: FIX

#314 feat(backoffice): 결제 취소 로직 추가
  api-backoffice/src/main/kotlin/com/inner/circle/apibackoffice/controller/PaymentController.kt
  api-backoffice/src/main/kotlin/com/inner/circle/apibackoffice/controller/dto/TransactionStatus.kt
  api-backoffice/src/main/kotlin/com/inner/circle/apibackoffice/controller/request/CancelPaymentRequest.kt
  core-backoffice/src/main/kotlin/com/inner/circle/corebackoffice/domain/TransactionStatus.kt
  core-backoffice/src/main/kotlin/com/inner/circle/corebackoffice/service/TransactionService.kt
  core-backoffice/src/main/kotlin/com/inner/circle/corebackoffice/service/dto/TransactionDto.kt
  core-backoffice/src/main/kotlin/com/inner/circle/corebackoffice/usecase/CancelPaymentUseCase.kt
  infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/adaptor/PaymentAdaptor.kt
  infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/adaptor/TransactionAdaptor.kt
  infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/adaptor/dto/PaymentDto.kt
  infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/port/SaveTransactionPort.kt
  infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/repository/TransactionRepository.kt
  infra-backoffice/src/main/kotlin/com/inner/circle/infrabackoffice/repository/TransactionRepositoryImpl.kt
Labels: FEAT

#322 fix(payment, backoffice): 시간 검증 로직 수정
  core-backoffice/src/main/kotlin/com/inner/circle/corebackoffice/service/TransactionService.kt
  core/src/main/kotlin/com/inner/circle/core/service/TransactionService.kt
Labels: REFACTOR
