Repository FC-InnerCircle-ICD2/fintech-BE, pull requests merged in 2025-01, with the labels that each got.

#54 Api Response LocalDatetime 규격화
  api/src/main/kotlin/com/inner/circle/api/util/serializer/KstDateTimeSerializer.kt
Labels: FEAT

#55 No Arg Plug in 추가 및 엔티티 명 단수로 변경
  infra/build.gradle.kts
  infra/src/main/resources/application-postgres.yaml
Labels: REFACTOR

#52 Feat/payments
  api/build.gradle.kts
  api/src/main/kotlin/com/inner/circle/api/config/SwaggerConfig.kt
  api/src/main/kotlin/com/inner/circle/api/payment/controller/ClaimApi.kt
  api/src/main/kotlin/com/inner/circle/api/payment/controller/ClaimController.kt
  api/src/main/kotlin/com/inner/circle/api/payment/exception/GlobalExceptionHandler.kt
  api/src/main/kotlin/com/inner/circle/api/payment/interceptor/AuthCheckInterceptor.kt
  api/src/main/kotlin/com/inner/circle/api/payment/interceptor/RequireAuth.kt
  api/src/main/kotlin/com/inner/circle/api/structure/dto/PaymentClaimRequest.kt
  api/src/main/kotlin/com/inner/circle/api/structure/dto/PaymentError.kt
  api/src/main/kotlin/com/inner/circle/api/structure/dto/PaymentResponse.kt
  api/src/main/kotlin/com/inner/circle/api/util/serializer/KstDateTimeSerializer.kt
  api/src/main/resources/application.yaml
  infra/build.gradle.kts
  infra/src/main/kotlin/com/inner/circle/infra/structure/adaptor/PaymentAdaptor.kt
  infra/src/main/kotlin/com/inner/circle/infra/structure/config/DataSourceConfig.kt
  infra/src/main/kotlin/com/inner/circle/infra/structure/repository/JpaConfiguration.kt
  infra/src/main/kotlin/com/inner/circle/infra/structure/repository/PaymentMemoryRepository.kt
  infra/src/main/kotlin/com/inner/circle/infra/structure/repository/PaymentRepository.kt
  infra/src/main/kotlin/com/inner/circle/infra/structure/repository/entity/AccountEntity.kt
  infra/src/main/kotlin/com/inner/circle/infra/structure/repository/entity/BaseEntity.kt
  infra/src/main/kotlin/com/inner/circle/infra/structure/repository/entity/MerchantEntity.kt
  infra/src/main/kotlin/com/inner/circle/infra/structure/repository/entity/PaymentEntity.kt
  infra/src/main/kotlin/com/inner/circle/infra/structure/repository/entity/PaymentRequest.kt
  infra/src/main/kotlin/com/inner/circle/infra/structure/repository/entity/TransactionEntity.kt
  infra/src/main/resources/application-postgres.yaml
Labels: FEAT

#76 Exception 모듈 및 공통 클래스 추가
  api-backoffice/build.gradle.kts
  api/build.gradle.kts
  api/src/main/kotlin/com/inner/circle/api/common/response/AppExceptionResponse.kt
  api/src/main/kotlin/com/inner/circle/api/payment/exception/GlobalExceptionHandler.kt
  core-backoffice/build.gradle.kts
  core/build.gradle.kts
  exception/src/main/kotlin/com/inner/circle/exception/AppException.kt
  exception/src/main/kotlin/com/inner/circle/exception/HttpStatus.kt
  exception/src/main/kotlin/com/inner/circle/exception/PaymentException.kt
  infra-backoffice/build.gradle.kts
  infra/build.gradle.kts
  settings.gradle.kts
Labels: FEAT

#89 Refactoring 카드 인증
  infra/src/main/kotlin/com/inner/circle/infra/structure/adaptor/CardPaymentAuthAdaptor.kt
  infra/src/main/kotlin/com/inner/circle/infra/structure/config/ExternalClientConfig.kt
  infra/src/main/kotlin/com/inner/circle/infra/structure/externalApi/CardAuthClient.kt
Labels: REFACTOR

#90 chore: Source Lint 맞춤 및 ide warning 요소 제거
  api/src/main/kotlin/com/inner/circle/api/sse/controller/SseApiController.kt
  infra/src/main/kotlin/com/inner/circle/infra/structure/adaptor/MobilePaymentAdaptor.kt
  infra/src/main/kotlin/com/inner/circle/infra/structure/adaptor/SaveUserCardAdaptor.kt
  infra/src/main/kotlin/com/inner/circle/infra/structure/repository/PaymentRequestRepository.kt
  infra/src/main/kotlin/com/inner/circle/infra/structure/repository/PaymentRequestRepositoryImpl.kt
  infra/src/main/kotlin/com/inner/circle/infra/structure/repository/UserCardRepository.kt
  infra/src/main/kotlin/com/inner/circle/infra/structure/repository/UserCardRepositoryImpl.kt
Labels: CHORE

#94 feat: Mock Server Base Url 프로퍼티로 관리 되도록 변경
  api/src/main/resources/application.yaml
  infra/src/main/kotlin/com/inner/circle/infra/structure/config/ExternalClientConfig.kt
  infra/src/main/resources/application-infra.yaml
Labels: FEAT

#95 chore: Log IDE Warning 요소 제거
  infra-backoffice/src/main/resources/application-datasource.yaml
  infra/src/main/resources/application-infra.yaml
Labels: CHORE
